/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 knight.gltf --types 
Author: Ulrik Langvandsbråten (https://sketchfab.com/best3deu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plated-knight-medieval-24fd61c662414344bcb81ddc62fd1e3b
Title: Plated Knight - Medieval
*/

import * as THREE from "three";
import { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { easing } from "maath";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    ["MannequinObject011_13_-_Default_0"]: THREE.Mesh;
    ["MannequinObject001cc001_09_-_Default_0"]: THREE.Mesh;
    ["MannequinObject001ccc_11_-_Default_0"]: THREE.Mesh;
    ["MannequinBox001xcsa001_12_-_Default_0"]: THREE.Mesh;
    ["MannequinObject008_10_-_Default_0"]: THREE.Mesh;
    ["MannequinBox001cc001_06_-_Default_0"]: THREE.Mesh;
    ["MannequinBox001bdfbdf001_08_-_Default_0"]: THREE.Mesh;
    ["MannequinBox013_07_-_Default_0"]: THREE.Mesh;
    ["Box001_15_-_Default_0"]: THREE.Mesh;
    ["flower_14_-_Default_0"]: THREE.Mesh;
    ["flower1_05_-_Default_0"]: THREE.Mesh;
    ["flower005_05_-_Default_0"]: THREE.Mesh;
    ["flower006_05_-_Default_0"]: THREE.Mesh;
    ["flower007_05_-_Default_0"]: THREE.Mesh;
    ["flower008_05_-_Default_0"]: THREE.Mesh;
    ["flower009_05_-_Default_0"]: THREE.Mesh;
    ["flower010_14_-_Default_0"]: THREE.Mesh;
    ["flower011_14_-_Default_0"]: THREE.Mesh;
  };
  materials: {
    ["13_-_Default"]: THREE.MeshStandardMaterial;
    ["09_-_Default"]: THREE.MeshStandardMaterial;
    ["11_-_Default"]: THREE.MeshStandardMaterial;
    ["12_-_Default"]: THREE.MeshStandardMaterial;
    ["10_-_Default"]: THREE.MeshStandardMaterial;
    ["06_-_Default"]: THREE.MeshStandardMaterial;
    ["08_-_Default"]: THREE.MeshStandardMaterial;
    ["07_-_Default"]: THREE.MeshStandardMaterial;
    ["15_-_Default"]: THREE.MeshStandardMaterial;
    ["14_-_Default"]: THREE.MeshStandardMaterial;
    ["05_-_Default"]: THREE.MeshStandardMaterial;
  };
};

const Knight = forwardRef<THREE.Group, JSX.IntrinsicElements["group"]>(
  (props, ref) => {
    const head = useRef<THREE.Group>(null!);
    const { nodes, materials } = useGLTF("/knight.gltf") as GLTFResult;

    useFrame((state, delta) => {
      easing.dampE(
        head.current.rotation,
        [0, 0, state.pointer.x * (state.camera.position.z > 1 ? 1 : -1)],
        0.4,
        delta
      );
    });

    return (
      <group ref={ref} {...props} dispose={null}>
        <group
          position={[-1.081, 0, 0.863]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.809}
        >
          <mesh
            geometry={nodes["MannequinObject011_13_-_Default_0"].geometry}
            material={materials["13_-_Default"]}
            position={[0.019, -27.002, 8.731]}
          />
          <mesh
            geometry={nodes["MannequinObject001cc001_09_-_Default_0"].geometry}
            material={materials["09_-_Default"]}
            position={[2.696, 0, 0]}
          />
          <mesh
            geometry={nodes["MannequinObject001ccc_11_-_Default_0"].geometry}
            material={materials["11_-_Default"]}
            position={[225.214, 0, 143.135]}
          />
          <mesh
            geometry={nodes["MannequinBox001xcsa001_12_-_Default_0"].geometry}
            material={materials["12_-_Default"]}
            position={[0.757, 0, 8.731]}
          />
          <mesh
            geometry={nodes["MannequinObject008_10_-_Default_0"].geometry}
            material={materials["10_-_Default"]}
            position={[0.047, 0, 8.731]}
          />
          <group ref={head}>
            {/* Head */}
            <mesh
              geometry={nodes["MannequinBox001cc001_06_-_Default_0"].geometry}
              material={materials["06_-_Default"]}
              position={[-21.909, 0, 8.731]}
            />
            {/* Head */}
          </group>
          <mesh
            geometry={nodes["MannequinBox001bdfbdf001_08_-_Default_0"].geometry}
            material={materials["08_-_Default"]}
            position={[91.951, 0, 8.731]}
          />
          <mesh
            geometry={nodes["MannequinBox013_07_-_Default_0"].geometry}
            material={materials["07_-_Default"]}
            position={[0.927, 6.886, 167.3]}
          />
        </group>
        <mesh
          geometry={nodes["Box001_15_-_Default_0"].geometry}
          material={materials["15_-_Default"]}
          position={[36.546, 0, -11.729]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 1, 0.784]}
        />
        <mesh
          geometry={nodes["flower_14_-_Default_0"].geometry}
          material={materials["14_-_Default"]}
          position={[39.698, 7.631, 8.167]}
          rotation={[0, 0.747, 0]}
          scale={[0.759, 0.637, 0.637]}
        />
        <mesh
          geometry={nodes["flower1_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
          position={[38.614, 1.376, 22.95]}
          rotation={[-Math.PI / 2, 0, 0.747]}
          scale={0.637}
        />
        <mesh
          geometry={nodes["flower005_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
          position={[41.269, 0.569, 0.331]}
          rotation={[-Math.PI / 2, 0, -0.378]}
          scale={0.637}
        />
        <mesh
          geometry={nodes["flower006_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
          position={[-41.052, 0.569, 20.866]}
          rotation={[-Math.PI / 2, 0, -0.378]}
          scale={0.637}
        />
        <mesh
          geometry={nodes["flower007_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
          position={[-1.682, 0.569, -31.706]}
          rotation={[-Math.PI / 2, 0, -0.378]}
          scale={0.637}
        />
        <mesh
          geometry={nodes["flower008_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
          position={[-22.435, 1.376, 32.174]}
          rotation={[-Math.PI / 2, 0, 0.747]}
          scale={0.637}
        />
        <mesh
          geometry={nodes["flower009_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
          position={[-38.112, 1.376, -16.653]}
          rotation={[-Math.PI / 2, 0, 0.747]}
          scale={0.637}
        />
        <mesh
          geometry={nodes["flower010_14_-_Default_0"].geometry}
          material={materials["14_-_Default"]}
          position={[-23.467, 7.631, 36.075]}
          rotation={[0, -1.47, 0]}
          scale={[0.759, 0.637, 0.637]}
        />
        <mesh
          geometry={nodes["flower011_14_-_Default_0"].geometry}
          material={materials["14_-_Default"]}
          position={[28.367, 7.631, -25.633]}
          rotation={[0, 1.544, 0]}
          scale={[0.759, 0.637, 0.637]}
        />
      </group>
    );
  }
);

useGLTF.preload("/knight.gltf");

export default Knight;
